import React, { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { 
  X, 
  Play, 
  Copy, 
  Check, 
  Sparkles, 
  ClipboardList, 
  CheckCircle2, 
  Bot, 
  FileText, 
  ArrowRight,
  ExternalLink,
  Video,
  Maximize2,
  Minimize2,
  Tv
} from 'lucide-react';

interface BulkPasteVideoModalProps {
  isOpen: boolean;
  onClose: () => void;
  onOpenBulkPasteWithSample?: (sampleText: string) => void;
}

const SAMPLE_AI_PROMPT = `Create 50 fill-in-the-blank questions on the topic of Passive Voice. Each question should have 4 multiple-choice options (A, B, C, and D) and include the correct answer.`;

const SAMPLE_PASTE_DATA = `Passive Voice – 50 Multiple-Choice Questions

Choose the correct answer to complete each sentence.

1. The classroom _____ every morning by the cleaner.
A. cleans
B. is cleaned
C. cleaned
D. is cleaning
Answer: B. is cleaned

2. English _____ in many countries around the world.
A. speaks
B. is spoken
C. spoke
D. is speaking
Answer: B. is spoken

3. The windows _____ yesterday because they were very dirty.
A. cleaned
B. are cleaned
C. were cleaned
D. have cleaned
Answer: C. were cleaned

4. This book _____ by millions of people every year.
A. reads
B. is read
C. was reading
D. has read
Answer: B. is read

5. The new shopping mall _____ next month.
A. will open
B. will be opened
C. is opening
D. opened
Answer: B. will be opened`;

export function BulkPasteVideoModal({
  isOpen,
  onClose,
  onOpenBulkPasteWithSample,
}: BulkPasteVideoModalProps) {
  const [isVideoStarted, setIsVideoStarted] = useState(false);
  const [selectedStep, setSelectedStep] = useState(0);
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [copiedData, setCopiedData] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isInternalFullscreen, setIsInternalFullscreen] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Sync with document fullscreen state
  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    document.addEventListener('webkitfullscreenchange', handleFullscreenChange);

    // Initial check
    setIsFullscreen(!!document.fullscreenElement);

    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
      document.removeEventListener('webkitfullscreenchange', handleFullscreenChange);
    };
  }, []);

  // Keyboard accessibility: ESC to exit fullscreen or close, F to toggle fullscreen
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (isInternalFullscreen && !document.fullscreenElement) {
          setIsInternalFullscreen(false);
          e.stopPropagation();
        } else if (document.fullscreenElement) {
          document.exitFullscreen?.().catch(() => {});
        } else {
          onClose();
        }
      } else if ((e.key === 'f' || e.key === 'F') && !(e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement)) {
        e.preventDefault();
        toggleFullscreen();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, isInternalFullscreen, onClose]);

  const toggleFullscreen = async () => {
    try {
      if (!document.fullscreenElement && !isInternalFullscreen) {
        if (containerRef.current && containerRef.current.requestFullscreen) {
          await containerRef.current.requestFullscreen();
        } else {
          setIsInternalFullscreen(true);
        }
      } else {
        if (document.fullscreenElement && document.exitFullscreen) {
          await document.exitFullscreen();
        }
        setIsInternalFullscreen(false);
      }
    } catch {
      // Fallback to internal CSS full-screen mode if browser denies requestFullscreen
      setIsInternalFullscreen(prev => !prev);
    }
  };

  const steps = [
    {
      id: 1,
      title: "1. Prompt AI",
      subtitle: "ChatGPT, Claude, or Gemini",
      desc: "Ask AI to create 50 fill-in-the-blank questions with 4 choices (A, B, C, D) and specify the correct answer for each.",
      badge: "Prompting AI",
      icon: Bot,
      color: "text-blue-400",
      bg: "bg-blue-500/15",
      border: "border-blue-500/30",
    },
    {
      id: 2,
      title: "2. Copy Output",
      subtitle: "Highlight all text",
      desc: "Select all 50 questions generated by the AI model and copy to your clipboard with Ctrl+C (⌘+C).",
      badge: "Copy Output",
      icon: FileText,
      color: "text-purple-400",
      bg: "bg-purple-500/15",
      border: "border-purple-500/30",
    },
    {
      id: 3,
      title: "3. Bulk Paste & Divide",
      subtitle: "Paste directly into game",
      desc: "Click Bulk Paste, paste the copied text, and Bubble Pop instantly detects questions, options, and answers.",
      badge: "Auto-Divide",
      icon: ClipboardList,
      color: "text-cyan-400",
      bg: "bg-cyan-500/15",
      border: "border-cyan-500/30",
    },
    {
      id: 4,
      title: "4. Append & Play",
      subtitle: "Ready in 1 click",
      desc: "Click 'Append to End'. All 50 question cards and choice bubbles are immediately populated!",
      badge: "Ready to Play",
      icon: CheckCircle2,
      color: "text-emerald-400",
      bg: "bg-emerald-500/15",
      border: "border-emerald-500/30",
    },
  ];

  if (!isOpen) return null;

  const handleStartPlay = () => {
    setIsVideoStarted(true);
    setTimeout(() => {
      if (videoRef.current) {
        videoRef.current.play().catch(() => {});
      }
    }, 100);
  };

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(SAMPLE_AI_PROMPT);
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 2500);
  };

  const handleCopyData = () => {
    navigator.clipboard.writeText(SAMPLE_PASTE_DATA);
    setCopiedData(true);
    setTimeout(() => setCopiedData(false), 2500);
  };

  const handleTrySample = () => {
    if (onOpenBulkPasteWithSample) {
      onOpenBulkPasteWithSample(SAMPLE_PASTE_DATA);
    }
    if (document.fullscreenElement) {
      document.exitFullscreen?.().catch(() => {});
    }
    onClose();
  };

  const isTrulyFullscreen = isFullscreen || isInternalFullscreen;

  const modalContent = (
    <div
      ref={containerRef}
      className={`fixed inset-0 z-[100] flex flex-col bg-slate-950/95 text-slate-100 backdrop-blur-xl transition-all duration-200 ${
        isTrulyFullscreen 
          ? 'w-screen h-screen p-0 m-0' 
          : 'p-3 sm:p-6 items-center justify-center'
      }`}
      onClick={(e) => {
        if (e.target === containerRef.current && !isTrulyFullscreen) {
          onClose();
        }
      }}
    >
      {/* Modal Box */}
      <div 
        className={`flex flex-col bg-slate-900 border border-slate-800 shadow-2xl transition-all duration-300 overflow-hidden ${
          isTrulyFullscreen
            ? 'w-full h-full rounded-none border-none'
            : 'w-full max-w-5xl rounded-3xl max-h-[92vh]'
        }`}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Navigation Header */}
        <div className="px-5 sm:px-6 py-3.5 bg-slate-900/90 border-b border-slate-800 flex items-center justify-between gap-4 shrink-0 backdrop-blur-md">
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-9 h-9 rounded-xl bg-blue-600 text-white flex items-center justify-center shadow-lg shadow-blue-500/20 shrink-0">
              <Video size={18} />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-base sm:text-lg font-black text-white tracking-wide truncate">
                  How to Bulk Paste Questions
                </h3>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-500/20 text-blue-300 border border-blue-500/30 shrink-0">
                  Video Guide
                </span>
                {isTrulyFullscreen && (
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 shrink-0 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                    Immersive Mode
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-400 truncate hidden sm:block">
                Generate 50+ multiple-choice questions with AI and auto-populate your game in seconds
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <a
              href="https://drive.google.com/file/d/1Q6HPdlNguMMimfkb2TADo44AqOOZCh7l/view?usp=sharing"
              target="_blank"
              rel="noreferrer"
              className="px-2.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs font-semibold flex items-center gap-1.5 border border-slate-700 transition-colors hidden md:flex"
              title="Open video in Google Drive"
            >
              <ExternalLink size={13} />
              <span>Drive Link</span>
            </a>

            {/* Fullscreen Toggle Button */}
            <button
              type="button"
              onClick={toggleFullscreen}
              className={`p-2 rounded-xl border transition-all cursor-pointer flex items-center gap-1.5 text-xs font-bold ${
                isTrulyFullscreen 
                  ? 'bg-blue-600 text-white border-blue-500 shadow-md shadow-blue-500/20' 
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border-slate-700'
              }`}
              title={isTrulyFullscreen ? "Exit Fullscreen (Esc or F)" : "Enter Fullscreen (F)"}
            >
              {isTrulyFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
              <span className="hidden sm:inline">
                {isTrulyFullscreen ? "Exit Fullscreen" : "Full Screen"}
              </span>
            </button>

            {/* Close Button */}
            <button
              type="button"
              onClick={() => {
                if (document.fullscreenElement) {
                  document.exitFullscreen?.().catch(() => {});
                }
                onClose();
              }}
              className="w-9 h-9 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center border border-slate-700 transition-colors cursor-pointer"
              title="Close (Esc)"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Content View: In Fullscreen, layout is wide and cinema-like; in normal mode, clean stacked dialog */}
        <div className={`flex-1 overflow-y-auto custom-scrollbar ${
          isTrulyFullscreen ? 'flex flex-col lg:flex-row' : 'flex flex-col p-4 sm:p-6 gap-6'
        }`}>
          
          {/* VIDEO STAGE CONTAINER */}
          <div className={`${
            isTrulyFullscreen 
              ? 'flex-[1.6] bg-black flex flex-col justify-center items-center p-3 sm:p-6 border-b lg:border-b-0 lg:border-r border-slate-800 relative' 
              : 'flex flex-col gap-2'
          }`}>
            <div className={`w-full relative rounded-2xl overflow-hidden bg-black border border-slate-800 shadow-2xl flex items-center justify-center group ${
              isTrulyFullscreen 
                ? 'max-h-[82vh] h-full aspect-video flex-1' 
                : 'aspect-video'
            }`}>
              {!isVideoStarted ? (
                /* High-impact Play Screen on Top */
                <div 
                  onClick={handleStartPlay}
                  className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-t from-black/95 via-slate-950/80 to-black/90 cursor-pointer text-white p-6 text-center z-10 transition-all hover:bg-black/70"
                >
                  <div className="relative mb-5">
                    <div className="w-20 h-20 sm:w-24 sm:h-24 rounded-full bg-blue-600 text-white flex items-center justify-center shadow-2xl shadow-blue-500/60 group-hover:scale-110 group-hover:bg-blue-500 transition-transform duration-300 ring-4 ring-blue-400/40">
                      <Play size={40} className="ml-1 fill-current" />
                    </div>
                    <span className="absolute -inset-2.5 rounded-full border border-blue-400/40 animate-ping pointer-events-none"></span>
                  </div>

                  <h4 className="text-lg sm:text-2xl font-black tracking-tight text-white mb-2">
                    Click to Play Video Tutorial
                  </h4>
                  <p className="text-xs sm:text-sm text-slate-300 max-w-md font-medium leading-relaxed mb-4">
                    Watch step-by-step how to prompt ChatGPT for 50 questions and instantly auto-divide them in Bubble Pop.
                  </p>

                  <div className="flex items-center gap-2.5 flex-wrap justify-center">
                    <span className="px-3 py-1 rounded-full bg-white/10 text-xs font-semibold text-slate-200 border border-white/10 flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                      1m 35s Video Walkthrough
                    </span>
                    <span className="px-3 py-1 rounded-full bg-blue-500/20 text-xs font-semibold text-blue-300 border border-blue-500/30 flex items-center gap-1">
                      <Tv size={12} />
                      1080p HD
                    </span>
                  </div>
                </div>
              ) : (
                <video
                  ref={videoRef}
                  src="/videos/bulk-paste-tutorial.mp4"
                  controls
                  autoPlay
                  playsInline
                  className="w-full h-full object-contain bg-black"
                >
                  <source src="/videos/bulk-paste-tutorial.mp4" type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              )}
            </div>

            {/* Quick playback helper hint */}
            {isTrulyFullscreen && (
              <div className="mt-2 text-center text-xs text-slate-500 hidden sm:flex items-center justify-center gap-3">
                <span>Press <kbd className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-300 font-mono text-[10px]">F</kbd> to toggle full screen</span>
                <span>•</span>
                <span>Press <kbd className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-300 font-mono text-[10px]">Esc</kbd> to exit</span>
              </div>
            )}
          </div>

          {/* OPTIONS COMPANION PANEL (Steps & Quick Actions) */}
          <div className={`${
            isTrulyFullscreen 
              ? 'flex-1 p-5 sm:p-6 flex flex-col gap-4 overflow-y-auto bg-slate-900/60 custom-scrollbar max-w-xl' 
              : 'flex flex-col gap-4 pt-1 border-t border-slate-800'
          }`}>
            <div>
              <h4 className="text-sm sm:text-base font-black text-white flex items-center gap-2">
                <span>How to Bulk Paste Questions</span>
              </h4>
              <p className="text-xs text-slate-400">
                Follow these 4 simple steps to populate full question banks in seconds:
              </p>
            </div>

            {/* Steps List */}
            <div className={`grid gap-3 ${isTrulyFullscreen ? 'grid-cols-1' : 'grid-cols-1 sm:grid-cols-2'}`}>
              {steps.map((s, index) => {
                const IconComponent = s.icon;
                const isSelected = selectedStep === index;
                return (
                  <div
                    key={s.id}
                    onClick={() => setSelectedStep(index)}
                    className={`p-3.5 sm:p-4 rounded-2xl border transition-all cursor-pointer flex flex-col justify-between gap-2.5 ${
                      isSelected 
                        ? `${s.bg} ${s.border} ring-1 ring-blue-500/40 shadow-md` 
                        : "bg-slate-800/60 border-slate-800 hover:border-slate-700 hover:bg-slate-800"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-2.5">
                        <div className={`w-8 h-8 rounded-xl ${s.bg} ${s.color} flex items-center justify-center shrink-0 font-bold border ${s.border}`}>
                          <IconComponent size={16} />
                        </div>
                        <div>
                          <div className="text-xs font-black text-white">
                            {s.title}
                          </div>
                          <div className="text-[11px] text-slate-400 font-medium">
                            {s.subtitle}
                          </div>
                        </div>
                      </div>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md ${s.bg} ${s.color}`}>
                        {s.badge}
                      </span>
                    </div>

                    <p className="text-xs text-slate-300 leading-relaxed">
                      {s.desc}
                    </p>

                    {/* Step specific interactive tools */}
                    {index === 0 && (
                      <div className="pt-2 border-t border-slate-800 flex items-center justify-between gap-2">
                        <span className="text-[11px] font-mono text-slate-400 truncate">
                          "Create 50 fill-in-the-blank..."
                        </span>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleCopyPrompt();
                          }}
                          className="px-2.5 py-1 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-[11px] font-bold flex items-center gap-1 cursor-pointer transition-colors shadow-sm shrink-0 active:scale-95"
                        >
                          {copiedPrompt ? <Check size={12} className="text-emerald-300" /> : <Copy size={12} />}
                          <span>{copiedPrompt ? "Copied Prompt!" : "Copy Prompt"}</span>
                        </button>
                      </div>
                    )}

                    {index === 1 && (
                      <div className="pt-2 border-t border-slate-800 flex items-center justify-between gap-2">
                        <span className="text-[11px] text-slate-400">5 Passive Voice Qs ready</span>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleCopyData();
                          }}
                          className="px-2.5 py-1 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-[11px] font-bold flex items-center gap-1 cursor-pointer transition-colors shadow-sm shrink-0 active:scale-95"
                        >
                          {copiedData ? <Check size={12} className="text-emerald-300" /> : <Copy size={12} />}
                          <span>{copiedData ? "Copied Sample!" : "Copy Sample Qs"}</span>
                        </button>
                      </div>
                    )}

                    {index === 2 && (
                      <div className="pt-2 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-400">
                        <span>Supports Q&A, A/B/C/D, or TSV</span>
                        <span className="text-cyan-400 font-bold">Auto-divides</span>
                      </div>
                    )}

                    {index === 3 && (
                      <div className="pt-2 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-400">
                        <span>Choices & answer keys mapped</span>
                        <span className="text-emerald-400 font-bold">Ready to Play</span>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Fast-Track CTA Banner */}
            <div className="mt-auto pt-2">
              <div className="bg-gradient-to-r from-blue-950/60 to-indigo-950/60 border border-blue-500/30 rounded-2xl p-4 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 shadow-lg">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 border border-blue-500/30">
                    <Sparkles size={20} />
                  </div>
                  <div>
                    <h5 className="text-xs sm:text-sm font-bold text-white">
                      Test it right now
                    </h5>
                    <p className="text-[11px] text-slate-300">
                      Pre-load sample questions directly into Bulk Paste
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleTrySample}
                    className="w-full sm:w-auto px-4 py-2 text-xs font-bold rounded-xl bg-blue-600 hover:bg-blue-500 text-white shadow-md shadow-blue-500/30 transition-all flex items-center justify-center gap-1.5 cursor-pointer active:scale-95"
                  >
                    <span>Try Sample in Bulk Paste</span>
                    <ArrowRight size={14} />
                  </button>
                </div>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
}
